config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'login',  to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'edit',   to: 'devise/registrations#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'play(/:team1)(/:team2)(/:user11)(/:user12)(/:user21)(/:user22)' => 'games#play', as: :play, via: [:get, :post]
  post 'games/save' => 'games#save'
  get 'games/end' => 'games#end', as: :after_end_screen
  get 'readme'     => 'pages#readme'
  get 'statistics' => 'pages#stats', as: :statistics

  get 'statistics/own' => 'statistics#own', as: :own_statistics
  match 'statistics/all(/:name)' => 'statistics#all', as: :all_statistics, via: [:get, :post]

  root 'welcome#index'
end

app/controllers/statistics_controller.rb
# TRY: give only 5 records to each ranking partial

class StatisticsController < ApplicationController
  before_action :set_user, only: [:all]

  @@user_not_in_database = :"Error: The given name does not match any registered user"
  @@selected_user_is_current_user = :"Error: Selected user must not be the current user"

  def own
    @user = current_user
  end

  def all
    # PROBLEMS
      # HOW TO HANDLE RANKINGS WHEN MORE TEAMS AND/OR USERS? Pagination? 3-7 items/page?
        # to display at once a great number of teams takes time
      # Efficiency
        # for 4 users, ~=200 games, ~=400 teams and ~=2000 goals- I must come back.
        # It should work well enough for 10 000 games, 20 000 teams, 200 users,
        # 150 000 users
        # Let's see if I could make it...
  end

  private
    def set_user
      @user_name_not_received = false
      @user_name_errors = false
      @user_name_error_messages = []

      user_name = params[:name]
      if user_name.nil?
        @user_name_not_received = true
      else
        set_errors user_name
      end
    end

    # how to write it better? Is this place good for this method?
    def set_errors(user_name)
      if current_user.name == user_name
        @user_name_errors = true
        @user_name_error_messages << @@selected_user_is_current_user
      end
      
      @user = User.find_by name: user_name
      if @user.nil?
        @user_name_errors = true
        @user_name_error_messages << @@user_not_in_database
      end 
    end

    def user_params # I must come back here to understand
      params.permit(:name)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
	# own statistics (use for all statistics too)
		# time_played: the total time user @user played
		# games_no: total number of games user @user played
		# goals_no: total number of goals user @user scored

		attr_reader :all_users, :all_games, :all_teams

		attr_reader :games_no, :goals_no

		def teams_from_db
			if @all_teams.nil?
				Team.includes(:team_statistic, :users)  # COME BACK!!!!!!!!!!!!!!! users are loaded two times! (one time here and one time above)
			else
				@all_teams
			end
		end

		# this data will be set for not doing some things more than once (e.g. execute @user.time_played)
		# how could i do this in a better way? (it should be bad to invoke this method from own
		# view - Could I use a callback instead?)
		def set_data_for_user
			@all_teams = teams_from_db
			user_statistic = @user.user_statistic
			@time_played = user_statistic.time_played
			@games_no = user_statistic.games_played_no
			@goals_no = user_statistic.goals_scored_no
		end

		# total time played by user @user in hours, minutes, seconds
		def time_played
			hours_minutes_seconds_from_seconds @time_played
		end

		# average time played per game in hours, minutes, seconds
		def avg_time
			average_time_per_game_in_seconds = divide @time_played, @games_no
			hours_minutes_seconds_from_seconds average_time_per_game_in_seconds
		end

		# average number of goals per game
		def avg_goals
			divide_and_round @goals_no, @games_no, 6
		end

				# three most frequent team members
		def three_most_frequent 
			@user.most_frequent_team_members 3, all_teams
		end



	# all statistics
		# selected user: no methods here, but the own statistics helper methods will be
		# invoked through user partial


		# Below, sum_no_wins_of_all_teams, sum_goals_no_of_all_teams, sum_wins_no_of_all_users,
		# sum_goals_no_of_all_users,sum_goals_no_of_all_users are not implemented methods. They are
		# just used to express tests.


		# teams_by_wins:
		# 	a test: sum_wins_no_of_all_teams == Game.count

		# teams_by_goals:
		#   a test: sum_goals_no_of_all_teams == sum_goals_no_of_all_users

		# users_by_wins:
		# 	a test: sum_wins_no_of_all_users == 2 * Game.count

		# users_by_goals:
		# 	a test: sum_goals_no_of_all_users == sum_goals_no_of_all_users
		attr_reader :teams_by_wins,
			:teams_by_goals,
			:users_by_wins,
			:users_by_goals,
			:all_time_goaler,
			:all_time_winner,
			:shortest_win_minutes,
			:longest_win_minutes,
			:most_popular_team,
			:least_popular_team,
			:teams_by_popularity

		# this data will be set for not doing some things more than once
		# how could i do this in a better way? (it should be bad to invoke
		# this method from all view - Could I use a callback instead?)
		# Should it be broken into more methods? I say yes, but first, I will try to increase efficiency.
		def set_data_for_all
			@all_teams = teams_from_db
			set_teams_by_wins_and_by_goals_and_popularity
			set_most_popular_team
			set_least_popular_team

			@all_users = User.includes(:user_statistic)
			set_users_by_wins_and_by_goals
			set_all_time_goaler
			set_all_time_winner

			@all_games = Game.all
			set_shortest_win_minutes
			set_longest_win_minutes
		end

		def set_teams_by_wins_and_by_goals_and_popularity
			@teams_by_wins = all_teams.order("team_statistics.wins_no DESC")
			@teams_by_goals = all_teams.order("team_statistics.goals_scored_no DESC")
			@teams_by_popularity = all_teams.order("team_statistics.games_played_no DESC")
		end

		def set_users_by_wins_and_by_goals
			@users_by_goals = all_users.order("user_statistics.goals_scored_no DESC")
			@users_by_wins = all_users.order("user_statistics.wins_no DESC")
		end

		def set_all_time_goaler
			@all_time_goaler = users_by_goals.first
		end

		def set_all_time_winner
			@all_time_winner = users_by_wins.first
		end

		def set_shortest_win_minutes
			@shortest_win_minutes = minutes_from_seconds all_games.minimum(:duration)
		end

		def set_longest_win_minutes
			@longest_win_minutes = minutes_from_seconds all_games.maximum(:duration)
		end
		
		def set_most_popular_team
			@most_popular_team = teams_by_popularity.last
		end

		def set_least_popular_team
			@least_popular_team = teams_by_popularity.first
		end

		def user?
			not @user.nil?
		end

		def user_name_not_received?
			@user_name_not_received
		end

		def user_name_errors?
			@user_name_errors
		end

		def user_name_error_messages
			@user_name_error_messages
		end


	# the below methods are more general applicability and used in more places in this class.
	# Should they be in StatisticsHelper?
  def divide(a, b)
    a.to_f/b.to_f
  end

  def modulo(a, b)
  	a.to_f % b.to_f
  end

  def divide_and_round(a, b, n=0)
    divide(a, b).round(n)
  end

  def modulo_and_round(a, b, n=0)
    modulo(a, b).round(n)
  end

  def divide_and_floor(a, b)
  	divide(a, b).floor
  end

  def modulo_and_floor(a, b)
  	modulo(a, b).floor
  end

  def minutes_from_seconds(seconds)
    divide_and_round seconds, 60
  end

  def hours_minutes_seconds_from_seconds(seconds)
    hours = divide_and_floor seconds, 3600
    mins = divide_and_floor seconds % 3600, 60
    secs = modulo_and_floor seconds % 3600, 60
    "#{hours} hour(s) #{mins} minute(s) #{secs} second(s)" 
  end

  def any_game_played?
    return false if Game.count == 0
    true
  end

end

app/views/statistics/_hall_of_fame.html.erb
<section>
	<h3 data-target="#hall-of-fame" data-toggle="collapse">
		Hall of Fame
	</h3>

	<ul id="hall-of-fame" class="collapse">
		<li>All time goaler [regardless of wins or not]:
				<%= render partial: "user_info", locals: {user: all_time_goaler, field_name: :goals_scored_no, what: :goals} %></li>
		
		<li>All time winner[counting only wins]:
			<%= render partial: "user_info", locals: {user: all_time_winner, field_name: :wins_no, what: :wins} %></li>
		
		<li>Shortest win [by number of minutes played]: <%= shortest_win_minutes %></li>
		
		<li>Longest win [by number of minutes played]: <%= longest_win_minutes %></li>
		
		<li>Most popular team [most games played together - regardless of winning or losing]: 
			<%= render partial: "team_info", locals: {team: most_popular_team, field_name: :games_played_no, what: :"popularity score"}%>
		</li>

		<li>Least popular team [regardless of winning or loosing]:
			<%= render partial: "team_info", locals: {team: least_popular_team, field_name: :games_played_no, what: :"popularity score"}%>
		</li>
	</ul>
</section>

app/views/statistics/_rankings.html.erb
<section>
	<h3 id="rankings-title" data-target="#rankings" data-toggle="collapse">
		Rankings
	</h3>
	
	<ul id="rankings" class="collapse">
		<li data-target="#teams-by-number-of-wins-ranking" data-toggle="collapse">
			Teams by number of wins
		</li>
		<section id="teams-by-number-of-wins-ranking" data-toggle="collapse">
			<%= render partial: "team_list", locals: {teams: teams_by_wins, field_name: :wins_no, what: :wins} %>
		</section>

		<li data-target="#teams-by-number-of-goals-ranking" data-toggle="collapse">
			Teams by number of goals [regardless of wins or not]
		</li>
		<section id="teams-by-number-of-goals-ranking" data-toggle="collapse">
			<%= render partial: "team_list", locals: {teams: teams_by_goals, field_name: :goals_scored_no, what: :goals} %>
		</section>

		<li data-target="#users-by-number-of-wins-ranking" data-toggle="collapse">
			Players by number of wins
		</li>
		<section id="users-by-number-of-wins-ranking" data-toggle="collapse">
			<%= render partial: "user_list", locals: {users: users_by_wins, field_name: :wins_no, what: :wins} %>
		</section>
		
		<li data-target="#users-by-number-of-goals-ranking" data-toggle="collapse">
			Players by number of goals [regardless of wins or not]
		</li>
		<section id="users-by-number-of-goals-ranking" data-toggle="collapse">
			<%= render partial: "user_list", locals: {users: users_by_goals, field_name: :goals_scored_no, what: :goals} %>
		</section>
	</ul>
</section>

app/views/statistics/_selected_user.html.erb
<section>
	<h3 data-target="#selected-user" data-toggle="collapse">
		Selected user (except yourself)
	</h3>

	<section id="selected-user" data-toggle="collapse">
		<%= render 'user_name_form' %>
	</section>

</section>

app/views/statistics/_selected_user_name_display.html.erb
<% if user? %>
	<section id="selected-user-display">Selected user: <%= @user.name %>
	</section>
<% end %>

app/views/statistics/_team_info.html.erb
<section>
		<ul>
			[<%= what %>: <%= team.team_statistic.send(field_name) %>]
			<% team.users.each do |user| %>
				<li> <%= user.name %> </li>
			<% end %>
		</ul>
</section>

app/views/statistics/_team_list.html.erb
<ol>
	<% teams.each do |team| %>
		<li> with <%= team.team_statistic.send(field_name)  %> <%= what %>:
			<ul>
				<% team.users.each do |user| %>
					<li> <%= user.name %> </li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ol>

app/views/statistics/_user.html.erb
<section id="user-statistics">
	<ul>
		<% set_data_for_user %>
		<li>Total number of games played: <%= games_no %></li>
		<li>Total number of goals scored: <%= goals_no %></li>
		<li>Total amount of time spent playing: <%= time_played %></li>
		<li>Average amount of time/game: <%= avg_time %></li>
		<li>Average number of goals scored per game: <%= avg_goals %></li>
		<li>Top 3 most frequent team members:
			<ol> 
				<% three_most_frequent.each do |team_member, frequency| %>
					<li><%= team_member.name %> (played <%= frequency %> times)</li>
				<% end %>
			</ol>
		</li>
	</ul>	
</section>

app/views/statistics/_user_info.html.erb
<section>
		<%= user.name %> (<%= user.user_statistic.send(field_name) %> <%= what %>)
</section>

app/views/statistics/_user_list.html.erb
<ol>
	<% users.each do |user, no| %>
		<li><%= user.name %> (<%= user.user_statistic.send(field_name) %> <%= what %>)</li>
	<% end %>
</ol>

app/views/statistics/_user_name_form.html.erb
<section id="selected-user-form">
	<%= form_for(all_statistics_path, method: "post") do %>		
		<%= label_tag :name %>
	  <%= text_field_tag :name, '', autofocus: true %>
	  <%= submit_tag :show %>

	  <% if user_name_errors? or user_name_not_received? %>
			<%= render 'user_name_form_errors' %>
		<% else %>
			<%= render 'selected_user_name_display' %>
			<%= render 'user' %>
		<% end %>
	<% end %>
</section>

app/views/statistics/_user_name_form_errors.html.erb
<section id='user-name-errors'>
	<ol> <% user_name_error_messages.each do |message|  %>
		<li> <%= message %> </li>
		<% end %>
	</ol>
</section>

app/views/statistics/all.html.erb
<h1>All Statistics</h1>
<main>
	<% if any_game_played? %>
		<% set_data_for_all %>
		<div class="container">
			<%= render 'selected_user' %>
			<%= render 'rankings' %>
			<%= render 'hall_of_fame' %>
		</div>
	<% else %>
		<h3>No game played yet!</h3>
	<% end %>
</main>

<section>
	<%=link_to "Back", statistics_path %>
</section>

app/views/statistics/own.html.erb
<h1>Own Statistics</h1>

<main>
	<% if any_game_played? %>
		<%= render 'user' %>
	<% else %>
		<h3>No game played yet!</h3>
	<% end %>
</main>

<section>
	<%=link_to "Back", statistics_path%>
</section>