config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'login',  to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'edit',   to: 'devise/registrations#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'play(/:team1)(/:team2)(/:user11)(/:user12)(/:user21)(/:user22)' => 'games#play', as: :play, via: [:get, :post]
  post 'games/save' => 'games#save'
  get 'games/end' => 'games#end', as: :after_end_screen
  get 'readme'     => 'pages#readme'
  get 'statistics' => 'pages#stats', as: :statistics

  get 'statistics/own' => 'statistics#own', as: :own_statistics
  match 'statistics/all(/:name)' => 'statistics#all', as: :all_statistics, via: [:get, :post]

  root 'welcome#index'
end

app/views/pages/readme.html.erb
<div>
  <h1 class="form-title"> About </h1>

  <h3 class="form-title"> A brief history of Foosball</h3>
  <p>It all started with a box of matches in England.</p>
  <p>Harold S. Thornton invented and patented foosball as it is known today in 1923, although some patents exist as far back as the 1890s.
    Thornton got the idea for foosball from watching his favorite soccer team, the Spurs. He wanted to create a game that in some way mirrored soccer but could be played at home.</p>
  <p>It doesn't stop there.</p>
  <p>He gained inspiration for the game when he lay individual matches across the box of matches.
    Thus, the idea of foosball was born.</p>
  <p>Thornton's uncle took his nephew's idea to the United States to have it patented there in 1927.
    The name foosball was later derived from the German word for "football," a sport better known as soccer in the U.S.</p>
  <p>Alejandro Finisterre thought this game would be fun for children who couldn't play soccer, so this form of recreational game was created as a result.</p>

  <h3 class="form-title"> Rules of Foosball</h3>
  <p>Foosball is started when one of two players places the ball through a serving hole on the side of the table. The first to serve can be decided by a coin toss.</p>
  <p>Once the ball is served, players use their rod-controlled figures, or foosballers, to hit the ball into their opponent's goal.</p>
  <p>Each side has four handlebars, so players can play one-on-one or two-on-two. If they play two on two, then generally each player controls two handlebars, either two defensive rows or two offensive rows.
    Any row can score.</p>
  <p>Spinning the handlebar 360 degrees to hit the ball is not allowed under organized foosball rules. However, in friendly matches, if both sides agree, then it is OK.</p>
  <p>The first person or team to score the predetermined number of goals, generally five or 10 depending on the scoreboard type on the table, is declared the winner.</p>
</div>
<%=link_to "Back", '/'%>

app/views/pages/stats.html.erb
<h1>Statistics</h1>
<main>
	<section>
		<%=link_to "Own Statistics", own_statistics_path %>
	</section>
	<section>
		<%=link_to "All Statistics", all_statistics_path %>
	</section>
	<section>
		<%=link_to "Back", '/'%>
	</section>
</main>