config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'login',  to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'edit',   to: 'devise/registrations#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'play(/:team1)(/:team2)(/:user11)(/:user12)(/:user21)(/:user22)' => 'games#play', as: :play, via: [:get, :post]
  post 'games/save' => 'games#save'
  get 'games/end' => 'games#end', as: :after_end_screen
  get 'readme'     => 'pages#readme'
  get 'statistics' => 'pages#stats', as: :statistics

  get 'statistics/own' => 'statistics#own', as: :own_statistics
  match 'statistics/all(/:name)' => 'statistics#all', as: :all_statistics, via: [:get, :post]

  root 'welcome#index'
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :teams
  has_many :users, through: :teams

  validate :exact_two_teams, :distinct_teams, :distinct_users
	@WIN_SCORE = 8

	# validations
		def exact_two_teams
			if teams.size != 2
				errors.add(:"for game:", "not two teams in game")
			end
		end
		
		def distinct_teams
			team1 = teams.first
			team2 = teams.second
			if teams.size == 2 and team1 == team2
				errors.add(:"for game:", "game cannot have same team twice")
			end
		end

		def distinct_users
			user1 = teams.first.users.first
			user2 = teams.first.users.second
			user3 = teams.second.users.first
			user4 = teams.second.users.second

			# user1 and user2, and user3 and user4 are distinct because team users are distinct
			if user1 == user3 or user1 == user4 or user2 == user3 or user2 == user4
				errors.add(:"for game", "must have distinct users")
			end
		end

		def self.new_with(duration, team1, team2)
			new_game = Game.new duration: duration
      new_game.teams << team1 << team2 
      new_game.save!
		end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :play_white_list_params, only: :play
  # before_action :congratulations_and_consolation_white_list_params,
  #   only: [:congratulations, :consolation]
  # before_action :in_white_list_params , only: :in
  protect_from_forgery with: :null_session
  # protect_from_forgery unless: -> { request.format.json? }
  before_action :update_database, only: :save

  attr_reader :team1_name,
    :team2_name,
    :user11, # team 1 user 1
    :user12, # team 1 user 2
    :user21, # ...
    :user22  # ...

  # for 'a just finished game'
  attr_reader :data,
    :duration,
    :team1_won,
    :team2_won,
    :u11, # user 1 of team 1
    :u12, # user 2 of team 1
    :u21, # ...
    :u22,
    :user11_goals_no,
    :user12_goals_no,
    :user21_goals_no,
    :user22_goals_no,
    :user11_own_goals_no,
    :user12_own_goals_no,
    :user21_own_goals_no,
    :user22_own_goals_no,
    :winner1,
    :winner2


  def play
    @new_game_errors_messages = []
    if request.post?
      analyze
      if no_errors
        render "in"
      end
    end
  end

  def save
    redirect_to after_end_screen_path(winner1: winner1, winner2: winner2)
  end

  def end
  end

  private
    def play_white_list_params
      if request.post?
        params.permit(:user11, :user12, :user21, :user22, :team1, :team2)
      end
    end

    def analyze_teams
      @team1_name = params[:team1]
      @team2_name = params[:team2]

      @new_game_errors_messages <<
        "team 1 has no name" if team1_name.empty?
      @new_game_errors_messages <<
        "team 2 has no name" if team2_name.empty?
      @new_game_errors_messages <<
        "teams have same name" if team1_name == team2_name
    end

    def analyze_users
      user11_name = params[:user11]
      user12_name = params[:user12]
      user21_name = params[:user21]
      user22_name = params[:user22]

      @new_game_errors_messages <<
        "user 1 of team 1 has no name" if user11_name.empty?
      @new_game_errors_messages <<
        "user 2 of team 1 has no name" if user12_name.empty?
      @new_game_errors_messages <<
        "user 1 of team 2 has no name" if user21_name.empty?
      @new_game_errors_messages <<
        "user 2 of team 2 has no name" if user22_name.empty?

      user_names = [] << user11_name << user12_name << user21_name << user22_name

      @new_game_errors_messages <<
        "some users have same name" if user_names.size != user_names.uniq.size

      @user11 = User.find_by name: params[:user11]
      @user12 = User.find_by name: params[:user12]
      @user21 = User.find_by name: params[:user21]
      @user22 = User.find_by name: params[:user22]

      @new_game_errors_messages <<
        "user \"#{user11}\" is not registered" if @user11.nil?
      @new_game_errors_messages <<
        "user \"#{user12}\" is not registered" if @user12.nil?
      @new_game_errors_messages <<
        "user \"#{user21}\" is not registered" if @user21.nil?
      @new_game_errors_messages <<
        "user \"#{user22}\" is not registered" if @user22.nil?
    end

    def analyze
      analyze_teams
      analyze_users
    end

    def no_errors
      @new_game_errors_messages.empty?
    end

    def set_game_data
      @data = JSON.parse(params[:game_data])
      @duration = data["duration"]
      team1 = data["team1"]
      team2 = data["team2"]

      user1 = "user1"
      user2 = "user2"
      won = "won"
      @team1_won = team1[won]
      @team2_won = team2[won]
      user11 = team1[user1]
      user12 = team1[user2]
      user21 = team2[user1]
      user22 = team2[user2]

      the_name = "name"
      goals = "goals"
      own_goals = "ownGoals"
      user11_name = user11[the_name]
      user12_name = user12[the_name]
      user21_name = user21[the_name]
      user22_name = user22[the_name]
      @u11 = User.find_by name: user11_name
      @u12 = User.find_by name: user12_name
      @u21 = User.find_by name: user21_name
      @u22 = User.find_by name: user22_name

      @user11_goals_no = user11[goals]
      @user12_goals_no = user12[goals]
      @user21_goals_no = user21[goals]
      @user22_goals_no = user22[goals]
      @user11_own_goals_no = user11[own_goals]
      @user12_own_goals_no = user12[own_goals]
      @user21_own_goals_no = user21[own_goals]
      @user22_own_goals_no = user22[own_goals]
    end

    def save_game_data
      all_teams = Team.includes(:users)
      team1 = Team.get_existing_or_new_team u11, u12, all_teams
      team2 = Team.get_existing_or_new_team u21, u22, all_teams

      u11.user_statistic.update_with team1_won,
        user11_goals_no,
        user11_own_goals_no,
        duration

      u12.user_statistic.update_with team1_won,
        user12_goals_no,
        user12_own_goals_no,
        duration

      u21.user_statistic.update_with team2_won,
        user21_goals_no,
        user21_own_goals_no,
        duration

      u22.user_statistic.update_with team2_won,
        user21_goals_no,
        user21_own_goals_no,
        duration

      team1.team_statistic.update_with team1_won,
        user11_goals_no + user12_goals_no,
        user11_own_goals_no + user12_own_goals_no,
        duration

      team2.team_statistic.update_with team2_won,
        user21_goals_no + user22_goals_no,
        user21_own_goals_no + user22_own_goals_no,
        duration

      Game.new_with duration, team1, team2

    end

    def set_winners
      if team1_won
        @winner1 = u11.name
        @winner2 = u12.name
      elsif team2_won
        @winner1 = u21.name
        @winner2 = u22.name
      end
    end

    def update_database
      set_game_data
      save_game_data
      set_winners
    end
end

app/helpers/games_helper.rb
module GamesHelper
	CONGRATULATIONS_MESSAGES = [] << 
		"\"Winners never quit and quitters never win.\" - Vince Lombardi" <<
		"\"It's about you. If you win, it's you; if you lose, it's you. Black and white. Nowhere to hide.\" - Greg Rusedski" <<
		"\"Win or lose, I'll feel good about myself. That's what is important.\" - Mary Docter" <<
		"That was a great game! You totally rocked!" <<
		"To more victories! Cheers and congratulations!" <<
		"Your team play was the best!" <<
		"Congratulations! I bet you are on cloud nine right now." <<
		"Congratulations to us!" <<
		"We are the champions! Congratulations to us, team!" <<
		"You ripped your opponent to pieces." <<
		"You ripped your opponent to pieces. That’s my boy!" <<
		"Congratulations! That’s my boy!" <<
		"Congratulations! You ripped your opponent to pieces. That’s my boy!" <<
		"Epic win!" <<
		"You totally owned them!" <<
		"Legendary!" <<
		"Godlike!" <<
		"Unstoppable!" <<
		"Dominating!"

	CONSOLATION_MESSAGES = [] <<
		"\"I would prefer even to fail with honor than win by cheating.\" - Sophocles" <<
		"\"Sometimes by losing a battle you find a new way to win the war.\" - Donald Trump" <<
		"\"First they ignore you, then they laugh at you, then they fight you, then you win.\" - Mahatma Gandhi" <<
		"\"Winners never quit and quitters never win.\" - Vince Lombardi" <<
		"\"You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.\" - Zig Ziglar" <<
		"\"You can't win unless you learn how to lose.\" - Kareem Abdul-Jabbar" <<
		"\"It's about you. If you win, it's you; if you lose, it's you. Black and white. Nowhere to hide.\" - Greg Rusedski" <<
		"\"Win or lose, I'll feel good about myself. That's what is important.\" - Mary Docter" <<
		"\"I want to have fun. It's a beautiful life. You learn, you win, you lose, but you get up.\" - Nas" <<
		"\"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.\" - Sun Tzu" <<
		"Well done, team. Congratulations for winning second place. The best is yet to come."

	def congratulations
		CONGRATULATIONS_MESSAGES[Random.rand(CONGRATULATIONS_MESSAGES.size)]
	end

	def consolation
		CONSOLATION_MESSAGES[Random.rand(CONSOLATION_MESSAGES.size)]
	end

	def errors
	  not @new_game_errors_messages.empty?
	end

	def new_game_errors_messages
		@new_game_errors_messages
	end
end

app/views/games/_new_game_form.html.erb
<section class="container" id="new-game-form" style="text-align:center">

  <% if errors %>
    <section id="new-game-form-errors">
      Errors:
      <ol id="new-game-form-errors">
        <% new_game_errors_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ol>
    </section>
  <% end %>

  <div class="row">
    <div class="col" style="color: #fff">
      <%= form_for(play_path, method: "post") do %>
        <%= label_tag :team1 %> <br>
        <%= text_field_tag :team1, '', autofocus: true %> <br>
        <%= label_tag :user11 %> <br>
        <%= text_field_tag :user11 %> <br>
        <%= label_tag :user12 %> <br>
        <%= text_field_tag :user12 %>
    </div>
    <div class="col" style="color: #fff">
      	<%= label_tag :team2 %> <br>
        <%= text_field_tag :team2 %> <br>
        <%= label_tag :user21 %> <br>
        <%= text_field_tag :user21 %> <br>
        <%= label_tag :user22 %> <br>
        <%= text_field_tag :user22 %> <br>
    </div>
	 </div>
        <br>

		  <%= submit_tag :Start %>
		<% end %>
</section>

app/views/games/_team.html.erb
<div>
	<div class="form-field" style="padding-bottom: 10px">
		<div>
			<h3 class="form-title"> Team <%= team_name %> </h3>
		</div>
		<div><strong>Score:<span id="team-<%= team_no %>-score-<%= @user11.id %>">0</span></strong></div>
	</div>

	<div>
		<%= render partial: "user", locals: {user: user1, co_user: user2, user_no: 1, team_no: team_no} %>
		<%= render partial: "user", locals: {user: user2, co_user: user1, user_no: 2, team_no: team_no} %>
	</div>
</div>

app/views/games/_user.html.erb
<div>
	<div class="form-field" style="padding-bottom: 5px">
		<%=image_tag user.gravatar_url, { width: 30, height: 30, class: "rounded-icon" }%>
		<strong id="team-<%= team_no %>-user-<%= user_no %>-<%= @user11.id %>"><%= user.name %></strong>
	</div>
	<div>
		<button onclick="goal(this)" id="<%= team_no %>-<%= user_no %>-<%= @user11.id %>" class="<%= @user11.id %>">Goal</button>
		<button onclick="ownGoal(this)" id="<%= team_no %>-<%= user_no %>-<%= @user11.id %>" class="<%= @user11.id %>">Own Goal</button>
	</div>
	<br>
</div>

app/views/games/end.html.erb
<div class="log-in" style="padding-top: 3%">
  <h1 class="form-title"><%= params[:winner1] %> and <%= params[:winner2] %> have won!</h1>
  <h5 class="form-field"><%= congratulations %></h5>
</div>

<div class="log-in" style="padding-top: 2%">
  <h1 class="form-title">For those who didn't win:</h1>
  <h5 class="form-field"><%= consolation %></h5>
</div>

app/views/games/in.html.erb
<section id="in" style="text-align:center">
	<br>
	<h1 class="form-title"> Foosball </h1>
	<br>
		<div class="left-half">
			<%= render partial: "team", locals: {team_name: @team1_name, team_no: 1, user1: @user11, user2: @user12} %>
		</div>

		<div class="right-half">
			<%= render partial: "team", locals: {team_name: @team2_name, team_no: 2, user1: @user21, user2: @user22} %>
		</div>

		<br>
		<br>
		<div>
			<div class="form-field" id="timer-<%= @user11.id %>" class="<%= @user11.id %>">00:00:00:0</div>
			<br>
			<button onclick="startOrPauseTimer(this)" class="<%= @user11.id %>">Start</button>
			<h2 id="timer-not-running-<%= @user11.id %>"></h2>
			<%=link_to "Abort Game", '/', :data => {:confirm => 'Abort game?'} %>
		</div>
</section>

app/views/games/play.html.erb
<div class="log-in">
  <h2 class="form-title">New game</h2>
  <%= render 'new_game_form' %>
  <br>
<!--  <div style="text-align:center">-->
    <%#=link_to "Back", '/'%>
<!--  </div>-->
</div>