config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'login',  to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'edit',   to: 'devise/registrations#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'play(/:team1)(/:team2)(/:user11)(/:user12)(/:user21)(/:user22)' => 'games#play', as: :play, via: [:get, :post]
  post 'games/save' => 'games#save'
  get 'games/end' => 'games#end', as: :after_end_screen
  get 'readme'     => 'pages#readme'
  get 'statistics' => 'pages#stats', as: :statistics

  get 'statistics/own' => 'statistics#own', as: :own_statistics
  match 'statistics/all(/:name)' => 'statistics#all', as: :all_statistics, via: [:get, :post]

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UpScore</title>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => 'image/ico' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <%= link_to image_tag("scoreup-logo.svg", width: 150), root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--  <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
  <!--    <ul class="navbar-nav mr-auto">-->
  <!--      <li class="nav-item active">-->
  <!--        <a class="nav-link" href="#">Play<span class="sr-only">(current)</span></a>-->
  <!--      </li>-->
  <!--      <li class="nav-item">-->
  <!--        <a class="nav-link" href="#">Link</a>-->
  <!--      </li>-->
  <!--    </ul>-->
  <!--  </div>-->

  <div class="navbar-collapse collapse order-3 dual-collapse2" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.gravatar_url, { width: 30, height: 30, class: "rounded-icon" } %>
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to 'About', readme_path, class: "dropdown-item" %>
            <%= link_to 'Statistcs', statistics_path, class: "dropdown-item" %>
            <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</nav>

<div class="big-container">
  <div class="container mh-100 h-100 mw-100 page-container">
    <div class="row h-100">
      <div class="col-md-2 col-lg-3 d-none d-md-block"></div>
      <div class="col-xs-12 col-md-8 col-lg-6">

        <%= yield %>

      </div>
      <div class="col-md-2 col-lg-3 d-none d-md-block"></div>
    </div>
  </div>
</div>
</body>
</html>